server:
  port: 8082
  servlet:
    context-path: /comments

spring:
  application.name: comment-service
  mongodb:
    uri: ${MONGO_ATLAS_URI}
    database: sample_mflix
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs